### ISSUE TITLE
Example server & client broken

### ISSUE THREAD

**Issue by canadaduane** [ryankurte/rust-daemon#4]
I've been trying to get a server/client running and turned to the example server/client in `src`. My code is failing so I tried to see if I could start from a "working state" using existing examples, but it looks like I can't get that to build either:

After `cargo build --features examples`:

```
error[E0463]: can't find crate for `serde_derive`
  --> src/examples/client.rs:21:1
   |
21 | extern crate serde_derive;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `serde_derive`
  --> src/examples/server.rs:21:1
   |
21 | extern crate serde_derive;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

If I can get the examples working, I think I can get my project using `daemon-engine`. Thanks for the abstraction!

**Comment by ryankurte** [comment]
hey no worries, i've fixed up and updated the examples, and good luck! tokio etc. can be a bit of a nightmare.
(you also might be interested in looking at [actix](https://github.com/actix/actix) depending on what you're working on, i've recently moved some projects from this to that)

**Comment by canadaduane** [comment]
Thanks, and I'll check it out!
